CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_roles (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    role VARCHAR(10) UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO user_roles(role)
VALUES ("admin"), ("user");

CREATE TABLE IF NOT EXISTS user_role_assign (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id INT UNIQUE NOT NULL,
    role_id INT NOT NULL DEFAULT 2,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_user
      FOREIGN KEY(user_id)
	  REFERENCES users(id)
	  ON DELETE CASCADE,
	CONSTRAINT fk_role
      FOREIGN KEY(role_id)
      REFERENCES user_roles(id)
      ON DELETE CASCADE
);
